module: LoggerAPI
author: IBM and Kitura
github_url: https://github.com/Kitura/LoggerAPI/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, LoggerAPI.xcodeproj, -target, LoggerAPI, LIBRARY_SEARCH_PATHS=.build/debug]

